--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend 
spec:
  selector:
    matchLabels:
      app: frontend 
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: service
        image: gcr.io/google-samples/microservices-demo/frontend:v0.5.2
        ports:
        - containerPort: 8080
        env:
        - name: PORT 
          value: "8080" 
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:5002" 
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:5004" 
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendationservice:5001" 
        - name: CART_SERVICE_ADDR
          value: "cartservice:5008"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice:5007"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:5005" 
        - name: AD_SERVICE_ADDR
          value: "adservice:5006"      
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend 
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8080
      nodePort: 30008 