apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart 
spec:
  selector:
    matchLabels:
      app: redis-cart 
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis
        image: redis:6.0-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name:  redis-data
          mountPath: /data 
      volumes:
      - name: redis-data
        emptyDir: {}    
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  type: ClusterIP
  selector:
    app: redis-cart 
  ports:
    - protocol: TCP
      port: 5009 
      targetPort: 6379         
